### ISSUE TITLE
Crop global land for precipitation datasets

### ISSUE THREAD

**Issue by imarkonis** [imarkonis/ithaca#7] opened 2023-01-19 08:19 UTC
We need a script for this saved in database/scripts

**Comment by imarkonis** [comment] 2023-01-19 11:08
Error: 

Error in compareRaster(x, mask) : different extent 

when applied in a cropped raster, e.g. era5_tp_mm_kenya_200101_201912_025_monthly.nc

**Comment by MiRoVaGo** [comment] 2023-01-20 09:50
The masking as is will work only on 0.25 resolution data (the common resolution for ithaca)
Should we close this issue or we want a mask that will work with any resolution? (for future/alternative uses)
I think masking with high-res shp file instead of using a raster mask would do the trick but needs to be tested

**Comment by imarkonis** [comment] 2023-01-23 13:36
Errors in GPCP
No lake masking in GPCC (because in their land mask they do not exclude lakes)
If need to re-run all, then please keep the lakes in.
Also see:   ithaca/database/scripts/03_b_how_to_use_masks.R - perhaps the example here might help

**Comment by MiRoVaGo** [comment] 2023-01-23 22:34
I checked the data. While the keep/drop lakes is still TBD
The missing value flag artifact is introduced during the cropping because it is not present on the global data
So the issue is on 01_crop_data.R
I suspect some of the brick metadata is lost when using foreach
I experienced something similar when looping a brick as a list of layers where the z axis information was lost
I fixed it by capturing the info before the loop and rewriting it after the loop (getZ() and set(z))
There is a similar function NAflag() so the solution probably is

foreach(dataset_count = 1:n_datasets_2000_2019) %dopar% {

*  dummie_flag <- NAflag(brick(prec_fnames_2000_2019[[dataset_count]]))

  result <- crop_space_time(brick(prec_fnames_2000_2019[[dataset_count]]), period_start, period_end, study_area)

*  NAflag(brick(prec_fnames_2000_2019[[dataset_count]])) <- dummie_flag

  writeRaster(result, filename = paste0(path_save_blueprint, prec_fnames_short_2000_2019[[dataset_count]], "_tp_mm_kenya_200006_201912_025_monthly.nc"), format= 'CDF')
}

**Closed** 2023-01-25 14:15 UTC
